

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins-server
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      # Il volume per salvare i dati di Jenkins
      - jenkins_home:/var/jenkins_home
      # Mounta il socket Docker dell'host nel container
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home: {}
