
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-server
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      # Il volume per salvare i dati di Jenkins
      - jenkins_home:/var/jenkins_home
      # Mounta il socket Docker dell'host nel container per permettere a Jenkins di eseguire comandi Docker.
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home: {}
