# monitoring/prometheus.yml


global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'sentiment-api'
    static_configs:
      
      - targets: ['sentiment-api-prod:8000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
