{
 "title": "Sentiment Analysis Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Suddivisione richieste per Status Code",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{job=\"sentiment-api\"}[$__rate_interval])) by (status_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latenza delle Richieste (95° percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_requests_latency_seconds_bucket{job=\"sentiment-api\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasso di Errore (5xx)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"sentiment-api\", status_code=~\"5..\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Richieste al Secondo",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"sentiment-api\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilizzo CPU (sentiment-api-prod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"sentiment-api\"}[5m])) by (container_label_com_docker_compose_service) * 100",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Utilizzo Memoria (sentiment-api-prod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_compose_service=\"sentiment-api\"}",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  }
 ]
}